server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true