server:
  port: 8081
  servlet:
    context-path: /ExcellentRoom

swagger2:
  enable: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true